
location: .gitman 
sources:
  - repo: git@mrs.fel.cvut.cz:uav/mrs_flight_forge_connector.git
    name: mrs_flight_forge_connertor 
    rev: master
    type: git
    sparse_paths:  ["src/", "include/"]