location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_flight_forge_connector.git
    name: mrs_flight_forge_connertor
    rev: master
    type: git
    params:
    sparse_paths:
      - src/
      - include/
    links:
      -
    scripts:
      -
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_flight_forge_connector.git
    name: mrs_flight_forge_connertor
    rev: 8af29bd8928463eb6d9c23352b826e1a011a40f8
    type: git
    params:
    sparse_paths:
      - src/
      - include/
    links:
      -
    scripts:
      -
default_group: ''
groups:
  -
