location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_flight_forge_connector.git
    name: mrs_flight_forge_connertor
    rev: master
    type: git
    params:
    sparse_paths:
      - src/
      - include/
    links:
      -
    scripts:
      -
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_flight_forge_connector.git
    name: mrs_flight_forge_connertor
    rev: 00484406019cdac495aebc019bae2f795156e07b
    type: git
    params:
    sparse_paths:
      - src/
      - include/
    links:
      -
    scripts:
      -
default_group: ''
groups:
  -
