location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_flight_forge_connector.git
    name: mrs_flight_forge_connertor
    rev: dev
    type: git
    params:
    sparse_paths:
      - src/
      - include/
    links:
      -
    scripts:
      -
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_flight_forge_connector.git
    name: mrs_flight_forge_connertor
    rev: 78cd151da9562a93d79771b8abdc197918d08a56
    type: git
    params:
    sparse_paths:
      - src/
      - include/
    links:
      -
    scripts:
      -
default_group: ''
groups:
  -
