location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_flight_forge_connector.git
    name: mrs_flight_forge_connertor
    rev: master
    type: git
    params:
    sparse_paths:
      - src/
      - include/
    links:
      -
    scripts:
      -
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_flight_forge_connector.git
    name: mrs_flight_forge_connertor
    rev: 189253315b0fac2dbe0bebc8537a544cb47263c4
    type: git
    params:
    sparse_paths:
      - src/
      - include/
    links:
      -
    scripts:
      -
default_group: ''
groups:
  -
