mrs_uav_managers:

  estimation_manager:

    state_estimators: [
     "gps_baro",
     "gps_garmin"
    ]

    initial_state_estimator: "gps_baro" # will be used as the first state estimator
    agl_height_estimator: "garmin_agl" # only slightly filtered height for checking min height (not used in control feedback)
