uav_names: [
  "uav1",
]

graphics_settings: "low"

# world_name: "warehouse" # works
world_name: "valley" # works

# TODO
# world_name: "cave" # does not work
# world_name: "dead_spruce_forest" # does not work
# world_name: "infinite_forest" # does not work
# world_name: "forest" # does not work

weather_type: "sunny"

daytime:
  hour: 7
  minute: 30

uav1:
  frame: "x500"
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 0.0
    heading: 0.0

sensors:

  lidar:
    enabled: true 
    # horizontal_rays: 256 # [-]
    # vertical_rays: 128 # [-]
    horizontal_rays: 128 # [-]
    vertical_rays: 32 # [-]
    offset_x: 0.0 # [m]
    offset_y: 0.0 # [m]
    offset_z: 0.1 # [m]
    rotation_pitch: 0.0 # [deg]
    rotation_roll: 0.0 # [deg]
    rotation_yaw: 0.0 # [deg]

    lidar_segmented:
      enabled: false 
      rate: 10.0 # [Hz]

  rgb:
    enabled: true 
    rgb_segmented:
      enabled: false 
      rate: 10.0 # [Hz]

  stereo:
    enabled: true
