uav_names: [
  "uav1",
]

ueds_world_level_name_enum: 6

uav1:
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 0.0
    heading: 0.0

sensors:
  lidar:
    enabled: true
  rgb:
    enabled: true
  stereo:
    enabled: true
