uav_names: [
  "uav1",
]

ueds_world_level_name_enum: 3


uav1:
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 0.0
    heading: 0.0

sensors:
  lidar:
    enabled: true
    horizontal_rays: 128 # [-]
    vertical_rays: 64 # [-]
    lidar_segmented:
      enabled: true
      rate: 10.0 # [Hz]
    lidar_intensity:
      enabled: trues
      rate: 10.0 # [Hz]

      values:
        grass: 50
        road: 7
        tree: 90
        building: 70
        fence: 40
        dirt_road: 30
        other: 155

      noise:
        enabled: true
        std_at_1m: 0.59 # [-]
        std_slope: 0.81 # [-] # multiplies std_at_1m for each meter of measured distances

  rgb:
    enabled: true
    offset_x: 0.0
  stereo:
    enabled: false
  rgb_segmented:
      enabled: false
      rate: 5.0 # [Hz]
