uav_names: [
  "uav1",
]

uav1:
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 0.0
    heading: 0.0

sensors:
  lidar:
    enabled: true
    horizontal_rays: 128 # [-]
    vertical_rays: 64 # [-]
    lidar_intensity:
      enabled: true 
      rate: 1.0 # [Hz]
  rgb:
    enabled: true
  stereo:
    enabled: true
