uavs_mutual_visibility: true

world_name: "valley"

weather_type: "sunny"

frames:
  world:
    name: "simulator_origin"
    prefix_with_uav_name: false
  fcu:
    name: "fcu"
    publish_tf: false

uav_names: [
  "uav1",
  "uav2",
]

uav1:
  frame: "x500"
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 0.0
    heading: 0


uav2:
  frame: "a300"
  type: "x500"
  spawn:
    x: 6.0
    y: 0.0
    z: 0.0
    heading: 3.14

sensors:

  rangefinder:

    enabled: true
    rate: 10.0 # [Hz]

  lidar:

    enabled: true

    rate: 10.0 # [Hz]

    horizontal_fov_left: 180.0 # [deg]
    horizontal_fov_right: 180.0 # [deg]
    
    vertical_fov_up: 52.0 # [deg]
    vertical_fov_down: 7.0 # [deg]
  rgb:
    enabled: true
  stereo:
    enabled: false
