ueds_world_level_name_enum: 0
frames:
  world:
    name: "simulator_origin"
    prefix_with_uav_name: false
  fcu:
    name: "fcu"
    publish_tf: false

uav_names: [
  "uav1",
  "uav2",
]

uav1:
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 0.0
    heading: 0


uav2:
  type: "x500"
  spawn:
    x: 6.0
    y: 0.0
    z: 0.0
    heading: 3.14

sensors:
  lidar:
    enabled: false
  rgb:
    enabled: false
  stereo:
    enabled: false
