hw_interface_plugin: "mrs_uav_unreal_simulation/Api"

gnss:
  utm_zone: "32U"
  utm_x: 446293.62
  utm_y: 5467958.49
  amsl: 460.0

input_mode:
  actuators:             false
  control_group:         false
  attitude_rate:         true
  attitude:              true
  acceleration_hdg_rate: false
  acceleration_hdg:      false
  velocity_hdg_rate:     false
  velocity_hdg:          false
  position:              false

  feedforward: true

outputs:
  gnss:                 true
  rtk:                  true
  imu:                  true
  altitude:             true
  magnetometer_heading: true
  rc_channels:          true
  battery_state:        true
  position:             true
  orientation:          true
  velocity:             true
  angular_velocity:     true
  odometry:             true
  ground_truth:         true
