simulation_rate: 250.0 # Hz
clock_rate: 250.0 # Hz

# desired realtime factor
realtime_factor: 1.0 # [-]

# if true, the RTF is automatically set such that the fastest sensor is always rendered at the desired rate
dynamic_rtf: true

# TODO describe
collisions: true

sensors:

  lidar:

    enabled: false

    rate: 10.0 # [Hz]

    horizontal_fov: 360.0 # [deg]
    vertical_fov: 90.0 # [deg]

    horizontal_rays: 256 # [-]
    vertical_rays: 128 # [-]

    offset_x: 0.0 # [m]
    offset_y: 0.0 # [m]
    offset_z: 0.06 # [m]

    rotation_pitch: 0.0 # [deg]
    rotation_roll: 0.0 # [deg]
    rotation_yaw: 0.0 # [deg]

    beam_length: 20.0 # [m]

    show_beams: false # TODO broken

    lidar_segmented:
      enabled: false
      rate: 10.0 # [Hz]

  rgb:
    enabled: false

    rate: 30.0 # [Hz]

    enable_hdr: true
    enable_temporal_aa: true
    enable_raytracing: true

    width: 640 # [px]
    height: 480 # [px]
    fov: 120.0 # [deg]

    offset_x: 0.14 # [m]
    offset_y: 0.0 # [m]
    offset_z: 0.0 # [m]

    rotation_pitch: 0.0 # [deg]
    rotation_yaw: 0.0 # [deg]
    rotation_roll: 0.0 # [deg]

    rgb_segmented:
      enabled: false
      rate: 5.0 # [Hz]

  stereo:

    enabled: false

    rate: 10.0 # [Hz]

    enable_hdr: true
    enable_temporal_aa: true
    enable_raytracing: true

    baseline: 0.1 # [m]

    width: 640 # [px]
    height: 480 # [px]
    fov: 90.0 # [deg]

    offset_x: 0.14 # [m]
    offset_y: 0.0 # [m]
    offset_z: 0.0 # [m]

    rotation_pitch: 20.0 # [deg]
    rotation_yaw: 0.0 # [deg]
    rotation_roll: 0.0 # [deg]

frames:
  world:
    name: "simulator_origin"
    prefix_with_uav_name: false
  fcu:
    name: "fcu"
    publish_tf: false
  rangefinder:
    name: "garmin"
    publish_tf: true

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: false

  bounds:
    x: 15.0 # [m]
    y: 15.0 # [m]
    z: 15.0 # [m]

# this virtual ground is simulated outside of Unreal
ground:
  enabled: false
  z: 0.0 # [m]

input_timeout: 1.0 # [s]

iterate_without_input: true

g: 9.81 # [ms^-2]

# * when enabled, this will place a temporary patch of ground just under the spawn location
# * this patch will disappear after the total_thrust > 0.9*hover_thrust
individual_takeoff_platform:
  enabled: true
